# import nbformat
# from nbconvert.preprocessors import ExecutePreprocessor

# filename = 'yolov5_detection.ipynb'
# with open(filename) as ff:
#     nb_in = nbformat.read(ff, nbformat.NO_CONVERT)
    
# ep = ExecutePreprocessor()

# nb_out = ep.preprocess(nb_in)



# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19hSNwl4BsidGGk86CZGUboWMAoMNHXFB
"""

from threading import Thread
import time

def category():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best.pt 

def brand():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best_brand.pt 
    
def color():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best_color.pt 

Thread(target=category).start()
Thread(target=brand).start()
Thread(target=color).start()