# Generated by Django 4.1.3 on 2022-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/products/shoes.jpg'),
        ),
    ]
