# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19hSNwl4BsidGGk86CZGUboWMAoMNHXFB
"""

from threading import Thread
import time

def category():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best.pt 

def brand():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best_brand.pt 
    
def color():
    !python detect.py --source /home/sandeep/Desktop/jutta.jpg --weights /home/sandeep/Desktop/major/yolo/yolov5/best_color.pt 

def model_result():
    Thread(target=category).start()
    Thread(target=brand).start()
    Thread(target=color).start()

model_result()
